[package]
name = "production_server"
version = "0.1.0"
authors = ["Icelk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvarn = { path = "../", default-features = false }
kvarn_extensions = { path = "../kvarn_extensions" }
http = "0.2.1"

[workspace]

[features]
default = ["kvarn/default"]
