[package]
name = "production_server"
version = "0.1.0"
authors = ["Icelk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvarn = { path = "../", default-features = false }
kvarn_extensions = { path = "../kvarn_extensions" }
http = "^0.2"
env_logger = "^0.8"
tokio = { version = "^1", features = ["macros"] }
log = "^0.4"
futures = "^0.3"

[workspace]

[features]
default = ["interactive", "kvarn/default"]
nc = ["kvarn/default", "kvarn/no-cache"]
production = ["kvarn/compression", "kvarn/fs", "kvarn/limiting"]

# Interactive program
interactive = []

# Run only on port 8080 for HTTP and 8443 for HTTPS instead of 80 and 443 for testing without root access
high_ports = []
