[package]
name = "production_server"
version = "0.1.0"
authors = ["Icelk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arktis = { path = "../" }
arktis_extensions = { path = "../arktis_extensions" }
http = "0.2.1"

[workspace]
