name: Test and build Mölla

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Clone kvarn
              run: git clone https://github.com/Icelk/kvarn ../kvarn
            - name: Clone kvarn-search
              run: git clone https://github.com/Icelk/kvarn-search ../kvarn-search
            - name: Clone kvarn-auth
              run: git clone https://github.com/Icelk/kvarn-auth ../kvarn-auth
            - name: Checking formatting
              run: cargo fmt --check
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings
            - name: Testing project
              run: cargo test
            - uses: Icelk/rustdoc-link-check@v2
              with:
                  private: true

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Clone kvarn
              run: git clone https://github.com/Icelk/kvarn ../kvarn
            - name: Clone kvarn-search
              run: git clone https://github.com/Icelk/kvarn-search ../kvarn-search
            - name: Clone kvarn-auth
              run: git clone https://github.com/Icelk/kvarn-auth ../kvarn-auth
            - name: Compile
              run: cargo build --profile distr -F bin --bin moella
            - name: Upload bin artefact
              uses: actions/upload-artifact@v3
              with:
                  name: moella
                  path: target/distr/moella
